### ISSUE TITLE
New image rollout generates down time

### ISSUE THREAD

**Issue by kelson42** [offspot/demo#10]
This is obviously not ideal as it give the impression to the user the solution "does not work" if it reaches right at that time. AFAIK this down-time can be more than just a few seconds.

It would be better if we could deploy to instances in paralell and then switch to the new one, only once it is ready.

**Comment by rgaudin** [comment]
>  it give the impression to the user the solution "does not work" if it reaches right at that time

This could be improved by changing the wording of the down phase. We could explain that a new image is being installed. We could even have a progress or whatever.

> It would be better if we could deploy to instances in paralell and then switch to the new one, only once it is ready.

It was not done on purpose because we were expecting TB-large image to be used in the demo and fitting two images on disk would not be possible (given the cost constraints).

Now that the main goal of the demo has changed and the image's size is always expected to be _small_, we can change that.

**Comment by kelson42** [comment]
> Now that the main goal of the demo has changed and the image's size is always expected to be _small_, we can change that.

Full suppport! Would be a nice improvement!

**Comment by rgaudin** [comment]
Closing as this is implemented and deployed. Merge to main will await @benoit74's review.
Old server has been terminated.
