### ISSUE TITLE
Proper branding is missing on homepage

### ISSUE THREAD

**Issue by kelson42** [offspot/demo#9]
See 
<img width="1024" alt="image" src="https://github.com/offspot/demo/assets/1029718/926fb18c-0230-4551-b7a0-750d53107efe">

… and already reported at https://github.com/offspot/imager-service/issues/409

Kiwix Hotspot name + logo should be clear and proeminent in title part of the dasboard in place of unstandard/unbranded wifi logo + „hotspot“.

**Comment by rgaudin** [comment]
This demo is not using the branding feature so it's using the default.

**Comment by kelson42** [comment]
@rgaudin What does that mean? It can not be done or it should not be done or it is not the right place to report. I want to put in emphase that I'm not really happy to have to report many times the same stuff and here I get a ticket closed without proper explanation?

**Comment by rgaudin** [comment]
My bad, I thought this was on dashboard repo 😵‍💫.

Your original issue was terrible which is why I had to create individual ones. I only created ones for the technical aspects that I would have to fix. The dashboard was indeed not using the branding from imager. This has been fixed and deployed 2d ago. So that technical `bug` is fixed.

For it to be visible on the demo, one (@Popolechien) has to set a specific branding image on the configuration otherwise it will use the default. Hence this ticket which is actually properly labelled and assigned 👍

I sense that you are not happy with the default branding image for the Hotspot ; please open a separate ticket (ideally in offpot-config) if that's the case..

**Comment by kelson42** [comment]
> I sense that you are not happy with the default branding image for the Hotspot ; please open a separate ticket (ideally in offpot-config) if that's the case..

Might be, even if I though this was clear:
* Name: Kiwix Hotspot https://github.com/kiwix/overview/wiki/Branding
* Logo: https://avatars.githubusercontent.com/u/87967336?s=200&v=4 ... or do we have a mix here between imager logo and Kiwix Hotspot logo?

**Comment by rgaudin** [comment]
>     * Name: Kiwix Hotspot https://github.com/kiwix/overview/wiki/Branding

`Own Name: Hotspot`.

I realize I did not include in project https://github.com/offspot/dashboard/issues/5 which would be in footer and different but maybe the fact that it's missing is confusing you.

>     * Logo: https://avatars.githubusercontent.com/u/87967336?s=200&v=4 ... or do we have a mix here between imager logo and Kiwix Hotspot logo?

This is not Hotspot logo (you'd agree that an SDcard is meaningless to Hotspot users). Actually we don't have a Hotspot logo which is why we decided to go with that WiFi-like icon that we have been using as favicon. We can discuss one with @simesie.
We've also made imager-service better at encouraging user to set custom image.
